#!/bin/bash

set -ouex pipefail

apt update -y

# Required packages
apt install -y $(cat /ctx/$DEBIAN_VER/dependencies | tr '\n' ' ')

# Use proper home directory for new users
sed -i 's|.*HOME=/home|HOME=/var/home|' "/etc/default/useradd"

# Enable mounts
systemctl enable home.mount
systemctl enable root.mount
systemctl enable srv.mount
systemctl enable mnt.mount
systemctl enable media.mount
systemctl enable opt.mount
systemctl enable usr-local.mount

# Fix permissions on sudoers.d
chmod 440 /etc/sudoers.d/001-bootc

# remove bls-garbage-collect from /etc/systemd/system/basic.garget.wants
rm -rf /etc/systemd/system/basic.target.wants/bls-garbage-collect.service
