#!/bin/bash

set -ouex pipefail

apt update -y

# Required packages
apt install -y $(cat /ctx/dependencies.${DEBIAN_VER} | tr '\n' ' ')

# add frostyard's repo
curl -fsSL https://repository.frostyard.org/public.key | gpg --dearmor -o /usr/share/keyrings/frostyard.gpg
echo "deb [signed-by=/usr/share/keyrings/frostyard.gpg] https://repository.frostyard.org/ stable main" > /etc/apt/sources.list.d/frostyard.list
apt update -y
apt install -y frostyard-nbc frostyard-updex

# Use proper home directory for new users
sed -i 's|.*HOME=/home|HOME=/var/home|' "/etc/default/useradd"

# Enable mounts
systemctl enable home.mount
systemctl enable root.mount
systemctl enable srv.mount
systemctl enable mnt.mount
systemctl enable media.mount
systemctl enable opt.mount
systemctl enable usr-local.mount

# Fix permissions on sudoers.d
chmod 440 /etc/sudoers.d/001-bootc

# Add build information to os-release
echo "BUILD_ID=\"$BUILD_ID\"" >> /usr/lib/os-release

# remove bls-garbage-collect from /etc/systemd/system/basic.garget.wants
rm -rf /etc/systemd/system/basic.target.wants/bls-garbage-collect.service
