#!/bin/bash

set -ouex pipefail

echo "::group::Executing install-bootloader"
trap 'echo "::endgroup::"' EXIT

# Remove unneeded repositories and update
rm -f /etc/apt/apt.conf.d/docker-gzip-indexes /etc/apt/apt.conf.d/docker-no-languages
rm -f /var/log/apt/eipp.log.xz
apt update -y

PKGS="grub-efi-amd64-signed- systemd systemd-boot"
[[ "${DEBIAN_VER}" == "forky" ]] && PKGS="${PKGS} systemd-ukify"

# Install systemd-boot, remove grub
apt install -y --allow-remove-essential $PKGS
